---
version: '3.7'
services:
  node:
    image: node:14.15.1-alpine3.12
    container_name: node
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "9005:9005"
    working_dir: "/app"

